package com.gennlife.rws.entity;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.google.common.collect.Lists;

import java.io.Serializable;
import java.util.List;

public class ActiveIndexConfig implements Serializable,Comparable<ActiveIndexConfig>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.active_index_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String activeIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.active_result_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String activeResultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.active_result
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String activeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.index_result_value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String indexResultValue;

    private String indexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.operator
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.operator_num
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String operatorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.function
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String function;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.function_param
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String functionParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.index_column
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String indexColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.index_column_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String indexColumnDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.search_scope
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String searchScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String mark;

    private String indexTypeDesc;

    private String isNotUsed;

    private String dateFormat;

    private String indexResultValueIsEqual;

    private Integer isOther;

    public Integer getIsOther() {
        return isOther;
    }

    public void setIsOther(Integer isOther) {
        this.isOther = isOther;
    }

    public String getIndexResultValueIsEqual() {
        return indexResultValueIsEqual;
    }

    public void setIndexResultValueIsEqual(String indexResultValueIsEqual) {
        this.indexResultValueIsEqual = indexResultValueIsEqual;
    }

    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    public String getIsNotUsed() {
        return isNotUsed;
    }

    public void setIsNotUsed(String isNotUsed) {
        this.isNotUsed = isNotUsed;
    }

    public String getIndexTypeDesc() {
        return indexTypeDesc;
    }

    public void setIndexTypeDesc(String indexTypeDesc) {
        this.indexTypeDesc = indexTypeDesc;
    }

    private List<ActiveIndexConfigCondition> conditions = Lists.newArrayList();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.id
     *
     * @return the value of active_index_config.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.id
     *
     * @param id the value for active_index_config.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.active_index_id
     *
     * @return the value of active_index_config.active_index_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getActiveIndexId() {
        return activeIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.active_index_id
     *
     * @param activeIndexId the value for active_index_config.active_index_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setActiveIndexId(String activeIndexId) {
        this.activeIndexId = activeIndexId == null ? null : activeIndexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.project_name
     *
     * @return the value of active_index_config.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.project_name
     *
     * @param projectName the value for active_index_config.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.active_result_desc
     *
     * @return the value of active_index_config.active_result_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getActiveResultDesc() {
        return activeResultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.active_result_desc
     *
     * @param activeResultDesc the value for active_index_config.active_result_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setActiveResultDesc(String activeResultDesc) {
        this.activeResultDesc = activeResultDesc == null ? null : activeResultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.active_result
     *
     * @return the value of active_index_config.active_result
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getActiveResult() {
        return activeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.active_result
     *
     * @param activeResult the value for active_index_config.active_result
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setActiveResult(String activeResult) {
        this.activeResult = activeResult == null ? null : activeResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.index_result_value
     *
     * @return the value of active_index_config.index_result_value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getIndexResultValue() {
        return indexResultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.index_result_value
     *
     * @param indexResultValue the value for active_index_config.index_result_value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setIndexResultValue(String indexResultValue) {
        this.indexResultValue = indexResultValue == null ? null : indexResultValue.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.operator
     *
     * @return the value of active_index_config.operator
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.operator
     *
     * @param operator the value for active_index_config.operator
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.operator_num
     *
     * @return the value of active_index_config.operator_num
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getOperatorNum() {
        return operatorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.operator_num
     *
     * @param operatorNum the value for active_index_config.operator_num
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setOperatorNum(String operatorNum) {
        this.operatorNum = operatorNum == null ? null : operatorNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.function
     *
     * @return the value of active_index_config.function
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.function
     *
     * @param function the value for active_index_config.function
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.function_param
     *
     * @return the value of active_index_config.function_param
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getFunctionParam() {
        return functionParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.function_param
     *
     * @param functionParam the value for active_index_config.function_param
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setFunctionParam(String functionParam) {
        this.functionParam = functionParam == null ? null : functionParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.index_column
     *
     * @return the value of active_index_config.index_column
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getIndexColumn() {
        return indexColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.index_column
     *
     * @param indexColumn the value for active_index_config.index_column
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setIndexColumn(String indexColumn) {
        this.indexColumn = indexColumn == null ? null : indexColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.index_column_desc
     *
     * @return the value of active_index_config.index_column_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getIndexColumnDesc() {
        return indexColumnDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.index_column_desc
     *
     * @param indexColumnDesc the value for active_index_config.index_column_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setIndexColumnDesc(String indexColumnDesc) {
        this.indexColumnDesc = indexColumnDesc == null ? null : indexColumnDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.search_scope
     *
     * @return the value of active_index_config.search_scope
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getSearchScope() {
        return searchScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.search_scope
     *
     * @param searchScope the value for active_index_config.search_scope
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setSearchScope(String searchScope) {
        this.searchScope = searchScope == null ? null : searchScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config.mark
     *
     * @return the value of active_index_config.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config.mark
     *
     * @param mark the value for active_index_config.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    public String getIndexType() {
        return indexType;
    }

    public void setIndexType(String indexType) {
        this.indexType = indexType;
    }

    public List<ActiveIndexConfigCondition> getConditions() {
        return conditions;
    }

    public void setConditions(List<ActiveIndexConfigCondition> conditions) {
        this.conditions = conditions;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("id", this.id)
                .add("indexResultValue", this.indexResultValue)
                .add("activeIndexId", this.activeIndexId)
                .add("projectName", this.activeResult)
                .add("activeResultDesc", this.activeResultDesc)
                .add("projectName",this.projectName)
                .add("function",this.function)
                .add("functionParam",this.functionParam)
                .add("indexColumn",this.indexColumn)
                .add("indexColumnDesc",this.indexColumnDesc)
                .add("indexType",this.indexType)
                .add("operator",this.operator)
                .add("operatorNum",this.operatorNum)
                .add("activeResult",this.activeResult)
                .toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        final ActiveIndexConfig other = (ActiveIndexConfig) obj;
        return Objects.equal(this.id, other.id) &&
                Objects.equal(this.indexResultValue, other.indexResultValue) &&
                Objects.equal(this.activeIndexId, other.activeIndexId) &&
                Objects.equal(this.activeResult, other.activeResult)&&
                Objects.equal(this.activeResultDesc,other.activeResultDesc)&&
                Objects.equal(this.function,other.function)&&
                Objects.equal(this.functionParam,other.functionParam)&&
                Objects.equal(this.indexColumn,other.indexColumn)&&
                Objects.equal(this.indexColumnDesc,other.indexColumnDesc)&&
                Objects.equal(this.indexType,other.indexType)&&
                Objects.equal(this.indexTypeDesc,other.indexTypeDesc)&&
                Objects.equal(this.operator,other.operator)&&
                Objects.equal(this.operatorNum,other.operatorNum)&&
                Objects.equal(this.activeResult,other.activeResult);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.id, this.indexResultValue, this.activeIndexId, this.projectName);
    }

    @Override
    public int compareTo(ActiveIndexConfig o) {
        if(this.equals(o)){
            return 0;
        }
        return 1;
    }
}