package com.gennlife.rws.entity;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.google.common.collect.Lists;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class ActiveIndex implements Serializable,Comparable<ActiveIndex>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.project_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.create_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.update_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.create_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.update_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String mark;

    private List<ActiveIndexConfig> config = Lists.newArrayList();

    private Integer activeType;

    private Integer isTmp;

    private String sortKey;

    private String confirmActiveId;
    private String dataGroup;

    private String crfId;
    private String isVariant;

    public String getIsVariant() {
        return isVariant;
    }

    public void setIsVariant(String isVariant) {
        this.isVariant = isVariant;
    }

    public String getCrfId() {
        return crfId;
    }

    public void setCrfId(String crfId) {
        this.crfId = crfId;
    }

    public String getDataGroup() {
        return dataGroup;
    }

    public void setDataGroup(String dataGroup) {
        this.dataGroup = dataGroup;
    }

    public String getConfirmActiveId() {
        return confirmActiveId;
    }

    public void setConfirmActiveId(String confirmActiveId) {
        this.confirmActiveId = confirmActiveId;
    }

    public String getSortKey() {
        return sortKey;
    }

    public void setSortKey(String sortKey) {
        this.sortKey = sortKey;
    }

    public Integer getIsTmp() {
        return isTmp;
    }

    public void setIsTmp(Integer isTmp) {
        this.isTmp = isTmp;
    }

    public Integer getActiveType() {
        return activeType;
    }

    public void setActiveType(Integer activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.id
     *
     * @return the value of active_index.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.id
     *
     * @param id the value for active_index.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.name
     *
     * @return the value of active_index.name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.name
     *
     * @param name the value for active_index.name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.project_id
     *
     * @return the value of active_index.project_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.project_id
     *
     * @param projectId the value for active_index.project_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.project_name
     *
     * @return the value of active_index.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.project_name
     *
     * @param projectName the value for active_index.project_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.create_time
     *
     * @return the value of active_index.create_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.create_time
     *
     * @param createTime the value for active_index.create_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.update_time
     *
     * @return the value of active_index.update_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.update_time
     *
     * @param updateTime the value for active_index.update_time
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.create_user
     *
     * @return the value of active_index.create_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.create_user
     *
     * @param createUser the value for active_index.create_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.update_user
     *
     * @return the value of active_index.update_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.update_user
     *
     * @param updateUser the value for active_index.update_user
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index.mark
     *
     * @return the value of active_index.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index.mark
     *
     * @param mark the value for active_index.mark
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    public List<ActiveIndexConfig> getConfig() {
        return config;
    }

    public void setConfig(List<ActiveIndexConfig> config) {
        this.config = config;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("id", this.id)
                .add("name", this.name)
                .add("projectId", this.projectId)
                .add("projectName", this.projectName)
                .toString();
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.id, this.name, this.projectId, this.projectName);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        final ActiveIndex other = (ActiveIndex) obj;
        return Objects.equal(this.id, other.id) && Objects
                .equal(this.projectId, other.projectId) && Objects
                .equal(this.projectName, other.projectName) && Objects
                .equal(this.name, other.name);
    }

    @Override
    public int compareTo(ActiveIndex o) {
        if(this.equals(o)){
            return 0;
        }
        return 1;
    }
}