package com.gennlife.rws.entity;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.google.common.collect.Lists;

import java.io.Serializable;
import java.util.List;

public class ActiveIndexConfigCondition implements Serializable,Comparable<ActiveIndexConfigCondition>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.active_index_config_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String activeIndexConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.source_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String sourceTagNameDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.source_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String sourceTagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.target_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String targetTagNameDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.target_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String targetTagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.operator_sign
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String operatorSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.ref_relation
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String refRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.logic_sing
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String logicSing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.ref_active_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String refActiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active_index_config_condition.parent_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    private String parentId;

    private String refActiveName;

    private Integer type;

    private Integer level;

    private String needPath;

    private String operatorSignDesc;

    private Integer conditionType;

    private String uuid;
    private String nodeType;
    private String before;
    private String after;
    private Integer acceptanceState;
    private String titleInfo;
    private String jsonType;

    private Integer innerLever;
    private Integer orde;
    private String titleType;
    private String childrenKey;
    private String enumActiveConfigId;

    public String getEnumActiveConfigId() {
        return enumActiveConfigId;
    }

    public void setEnumActiveConfigId(String enumActiveConfigId) {
        this.enumActiveConfigId = enumActiveConfigId;
    }

    public String getChildrenKey() {
        return childrenKey;
    }

    public void setChildrenKey(String childrenKey) {
        this.childrenKey = childrenKey;
    }

    public String getTitleType() {
        return titleType;
    }

    public void setTitleType(String titleType) {
        this.titleType = titleType;
    }

    public Integer getOrde() {
        return orde;
    }

    public void setOrde(Integer orde) {
        this.orde = orde;
    }

    public Integer getInnerLever() {
        return innerLever;
    }

    public void setInnerLever(Integer innerLever) {
        this.innerLever = innerLever;
    }

    public String getJsonType() {

        return jsonType;
    }

    public void setJsonType(String jsonType) {

        this.jsonType = jsonType;
    }

    public String getTitleInfo() {
        return titleInfo;
    }

    public void setTitleInfo(String titleInfo) {
        this.titleInfo = titleInfo;
    }

    public String getNodeType() {
        return nodeType;
    }

    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }

    public String getBefore() {
        return before;
    }

    public void setBefore(String before) {
        this.before = before;
    }

    public String getAfter() {
        return after;
    }

    public void setAfter(String after) {
        this.after = after;
    }

    public Integer getAcceptanceState() {
        return acceptanceState;
    }

    public void setAcceptanceState(Integer acceptanceState) {
        this.acceptanceState = acceptanceState;
    }

    private List<ActiveIndexConfigCondition> strongRef = Lists.newArrayList();

    public List<ActiveIndexConfigCondition> getStrongRef() {
        return strongRef;
    }

    public void setStrongRef(List<ActiveIndexConfigCondition> strongRef) {
        this.strongRef = strongRef;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Integer getConditionType() {
        return conditionType;
    }

    public void setConditionType(Integer conditionType) {
        this.conditionType = conditionType;
    }

    private List<ActiveIndexConfigCondition> details = Lists.newArrayList();

    public List<ActiveIndexConfigCondition> getDetails() {
        return details;
    }

    public String getOperatorSignDesc() {
        return operatorSignDesc;
    }

    public void setOperatorSignDesc(String operatorSignDesc) {
        this.operatorSignDesc = operatorSignDesc;
    }

    public void setDetails(List<ActiveIndexConfigCondition> details) {
        this.details = details;
    }

    public String getNeedPath() {
        return needPath;
    }

    public void setNeedPath(String needePath) {
        this.needPath = needePath;
    }

    private List<ActiveIndexConfigCondition> inner = Lists.newArrayList();

    private List<ActiveIndexConfigCondition> detail = Lists.newArrayList();

    public List<ActiveIndexConfigCondition> getDetail() {
        return detail;
    }

    public void setDetail(List<ActiveIndexConfigCondition> detail) {
        this.detail = detail;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }


    public List<ActiveIndexConfigCondition> getInner() {
        return inner;
    }

    public void setInner(List<ActiveIndexConfigCondition> inner) {
        this.inner = inner;
    }

    public String getRefActiveName() {
        return refActiveName;
    }

    public void setRefActiveName(String refActiveName) {
        this.refActiveName = refActiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.id
     *
     * @return the value of active_index_config_condition.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.id
     *
     * @param id the value for active_index_config_condition.id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.active_index_config_id
     *
     * @return the value of active_index_config_condition.active_index_config_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getActiveIndexConfigId() {
        return activeIndexConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.active_index_config_id
     *
     * @param activeIndexConfigId the value for active_index_config_condition.active_index_config_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setActiveIndexConfigId(String activeIndexConfigId) {
        this.activeIndexConfigId = activeIndexConfigId == null ? null : activeIndexConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.source_tag_name_desc
     *
     * @return the value of active_index_config_condition.source_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getSourceTagNameDesc() {
        return sourceTagNameDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.source_tag_name_desc
     *
     * @param sourceTagNameDesc the value for active_index_config_condition.source_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setSourceTagNameDesc(String sourceTagNameDesc) {
        this.sourceTagNameDesc = sourceTagNameDesc == null ? null : sourceTagNameDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.source_tag_name
     *
     * @return the value of active_index_config_condition.source_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getSourceTagName() {
        return sourceTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.source_tag_name
     *
     * @param sourceTagName the value for active_index_config_condition.source_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setSourceTagName(String sourceTagName) {
        this.sourceTagName = sourceTagName == null ? null : sourceTagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.target_tag_name_desc
     *
     * @return the value of active_index_config_condition.target_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getTargetTagNameDesc() {
        return targetTagNameDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.target_tag_name_desc
     *
     * @param targetTagNameDesc the value for active_index_config_condition.target_tag_name_desc
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setTargetTagNameDesc(String targetTagNameDesc) {
        this.targetTagNameDesc = targetTagNameDesc == null ? null : targetTagNameDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.target_tag_name
     *
     * @return the value of active_index_config_condition.target_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getTargetTagName() {
        return targetTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.target_tag_name
     *
     * @param targetTagName the value for active_index_config_condition.target_tag_name
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setTargetTagName(String targetTagName) {
        this.targetTagName = targetTagName == null ? null : targetTagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.operator_sign
     *
     * @return the value of active_index_config_condition.operator_sign
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getOperatorSign() {
        return operatorSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.operator_sign
     *
     * @param operatorSign the value for active_index_config_condition.operator_sign
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setOperatorSign(String operatorSign) {
        this.operatorSign = operatorSign == null ? null : operatorSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.ref_relation
     *
     * @return the value of active_index_config_condition.ref_relation
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getRefRelation() {
        return refRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.ref_relation
     *
     * @param refRelation the value for active_index_config_condition.ref_relation
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setRefRelation(String refRelation) {
        this.refRelation = refRelation == null ? null : refRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.logic_sing
     *
     * @return the value of active_index_config_condition.logic_sing
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getLogicSing() {
        return logicSing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.logic_sing
     *
     * @param logicSing the value for active_index_config_condition.logic_sing
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setLogicSing(String logicSing) {
        this.logicSing = logicSing == null ? null : logicSing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.ref_active_id
     *
     * @return the value of active_index_config_condition.ref_active_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getRefActiveId() {
        return refActiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.ref_active_id
     *
     * @param refActiveId the value for active_index_config_condition.ref_active_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setRefActiveId(String refActiveId) {
        this.refActiveId = refActiveId == null ? null : refActiveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.value
     *
     * @return the value of active_index_config_condition.value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.value
     *
     * @param value the value for active_index_config_condition.value
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active_index_config_condition.parent_id
     *
     * @return the value of active_index_config_condition.parent_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active_index_config_condition.parent_id
     *
     * @param parentId the value for active_index_config_condition.parent_id
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("id", this.id)
                .add("activeIndexConfigId", this.activeIndexConfigId)
                .add("sourceTagNameDesc", this.sourceTagNameDesc)
                .add("sourceTagName", this.sourceTagName)
                .add("targetTagNameDesc", this.targetTagNameDesc)
                .add("targetTagName",this.targetTagName)
                .add("operatorSign",this.operatorSign)
                .add("refRelation",this.refRelation)
                .add("logicSing",this.logicSing)
                .add("refActiveId",this.refActiveId)
                .add("value",this.value)
                .add("parentId",this.parentId)
                .toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        final ActiveIndexConfigCondition other = (ActiveIndexConfigCondition) obj;
        return Objects.equal(this.id, other.id) &&
                Objects.equal(this.activeIndexConfigId, other.activeIndexConfigId) &&
                Objects.equal(this.sourceTagNameDesc, other.sourceTagNameDesc) &&
                Objects.equal(this.sourceTagName, other.sourceTagName)&&
                Objects.equal(this.targetTagNameDesc,other.targetTagNameDesc)&&
                Objects.equal(this.targetTagName,other.targetTagName)&&
                Objects.equal(this.operatorSign,other.operatorSign)&&
                Objects.equal(this.refRelation,other.refRelation)&&
                Objects.equal(this.logicSing,other.logicSing)&&
                Objects.equal(this.value,other.value)&&
                Objects.equal(this.parentId,other.parentId)&&
                Objects.equal(this.refActiveId,other.refActiveId)&&
                Objects.equal(this.operatorSignDesc,other.operatorSignDesc);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.id, this.activeIndexConfigId, this.parentId);
    }

    @Override
    public int compareTo(ActiveIndexConfigCondition o) {
        if(this.equals(o)){
            return 0;
        }
        return 1;
    }

}