package com.gennlife.rws.dao;

import com.gennlife.rws.entity.ActiveIndexTask;

import java.util.List;
import java.util.Map;

public interface ActiveIndexTaskMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int insert(ActiveIndexTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int insertSelective(ActiveIndexTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    ActiveIndexTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int updateByPrimaryKeySelective(ActiveIndexTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_task
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int updateByPrimaryKey(ActiveIndexTask record);

    List<ActiveIndexTask> findByActiveId(String activeId );

    List<ActiveIndexTask> findByActiveIds(List<String> activeIds );

    List<ActiveIndexTask> findByActiveIdsAndStatus(Map<String,Object> param);

    void updateTaskStatus(Map<String, Object> param);

    void replace(ActiveIndexTask task);

    List<ActiveIndexTask> findByParam(Map<String,Object> param);

    public void updateTaskStatusToHistory(Map<String,Object> param);
}