package com.gennlife.rws.dao;

import com.gennlife.rws.entity.ActiveIndexConfigCondition;
import com.gennlife.rws.entity.ActiveIndexRelation;

import java.util.List;
import java.util.Map;

public interface ActiveIndexConfigConditionMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_config_condition
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int deleteByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_config_condition
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int insertSelective(ActiveIndexConfigCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_config_condition
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    //ActiveIndexConfigCondition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_config_condition
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int updateByPrimaryKeySelective(ActiveIndexConfigCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active_index_config_condition
     *
     * @mbggenerated Wed Oct 18 21:17:09 CST 2017
     */
    int updateByPrimaryKey(ActiveIndexConfigCondition record);

    void insertBatch(List<ActiveIndexConfigCondition> conditions);

    List<ActiveIndexConfigCondition> findAllByActiveIndexConfigId(String activeIndexConfigId);
    List<ActiveIndexConfigCondition> findByActiveIndexConfigId(String activeIndexConfigId);
    List<ActiveIndexConfigCondition> findByConfigIdParentIdNull(String activeIndexConfigId);
    void updateBatch(List<ActiveIndexConfigCondition> conditions);
    int countByParam(Map<String, Object> param);
    List<ActiveIndexConfigCondition> findByRefActiveId(String refActiveId);
    List<ActiveIndexConfigCondition> findByParentId(String refActiveId);
    void deleteByActiveIndexConfigId(String activeIndexConfigId);

    List<ActiveIndexConfigCondition> findByParentIdAndType(String parentId,Integer type);
    List<ActiveIndexConfigCondition> findByConfigIdAndType(String configId,Integer type);
    List<ActiveIndexConfigCondition> findByConfigIdAndTypeAndLevel(String configId,Integer type,Integer level);
    List<ActiveIndexConfigCondition> findByIdAndTypeAndLevel(String id,Integer type,Integer level);
    Integer findMaxLevelByConfigId(String configId);

    List<String> findConfigIdByRefActiveId(String activeId);

    List<String> findRefActiveIdByConfigId(List<String> configIds);
    List<ActiveIndexConfigCondition> findByConfigId(String configId);
    List<ActiveIndexConfigCondition> selectStrongRef(String configId);
    List<ActiveIndexRelation> selectRelation(Map<String, Object> param);
    List<ActiveIndexRelation> selectRelationByRefId(Map<String, Object> param);
    int listCountByParam(Map<String, Object> param);
    int updateRefNameByRefId(Map<String,Object> param);
}